version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    networks:
      - app-network
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: app_db
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
